'use client';
import {Component,useEffect,useRef,useState,type ReactNode} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {Html} from '@react-three/drei';
import {AdditiveBlending,Color,Vector3,type Group} from 'three';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {Galaxy} from './galaxy';
import {workItems} from './services';
const colors=['#39c8ff','#ffd84a','#ff5a70'];
const roadmap=[{name:'메인',english:'HOME',target:0},{name:'소개',english:'ABOUT',target:1},{name:'연혁',english:'HISTORY',target:2}];
const galaxyLinks=[{name:'소개',position:[-3.7,.9,0] as [number,number,number],target:1},{name:'연혁',position:[3.8,1.15,-.5] as [number,number,number],target:2}];
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?null:this.props.children}}
function SectionLight({item,index,active,reduced,onChoose}:{item:(typeof galaxyLinks)[number];index:number;active:number;reduced:boolean;onChoose:(i:number)=>void}){
 const group=useRef<Group>(null),target=useRef(new Vector3()),scale=useRef(new Vector3());
 useFrame(({clock,size},delta)=>{if(!group.current)return;const mobile=size.width<700;target.current.set(item.position[0]*(mobile?.55:1.15),item.position[1]*(mobile?1.05:1.25),item.position[2]);if(!reduced)target.current.y+=Math.sin(clock.elapsedTime*.35+index)*.07;group.current.position.lerp(target.current,reduced?1:Math.min(delta*3.5,1));scale.current.setScalar(active===0?1:.25);group.current.scale.lerp(scale.current,reduced?1:Math.min(delta*3,1))});
 return <group ref={group} position={item.position}><mesh onClick={()=>onChoose(item.target)}><planeGeometry args={[2.2,2.2]}/><shaderMaterial transparent depthWrite={false} blending={AdditiveBlending} toneMapped={false} uniforms={{lightColor:{value:new Color(colors[index])}}} vertexShader={'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'} fragmentShader={'uniform vec3 lightColor;varying vec2 v;void main(){vec2 p=v-.5;float r=length(p);float h=exp(-r*9.0)*.65;float c=exp(-r*r*1500.0);float x=(exp(-abs(p.x)*170.0)*exp(-abs(p.y)*14.0)+exp(-abs(p.y)*170.0)*exp(-abs(p.x)*14.0))*.5;float a=min(1.0,h+c+x);gl_FragColor=vec4(mix(lightColor,vec3(1.0),c*.76),a);}'}/></mesh>{active===0&&<Html center position={[0,-.6,.1]} zIndexRange={[5,0]}><button className="section-light-label" onClick={()=>onChoose(item.target)}><strong>{item.name}</strong><ArrowUpRight size={14}/></button></Html>}</group>
}
function Camera({active,reduced}:{active:number;reduced:boolean}){const target=useRef(new Vector3());useFrame(({camera,pointer,size},delta)=>{target.current.set(reduced?0:pointer.x*.7,reduced?0:pointer.y*.35,(active?15:16)*Math.max(1,.85/(size.width/size.height)));camera.position.lerp(target.current,reduced?1:Math.min(delta*2.5,1));camera.lookAt(0,0,0)});return null}
export default function Home(){
 const[active,setActive]=useState(0),[reduced,setReduced]=useState(false);const root=useRef<HTMLDivElement>(null!),scroll=useRef<HTMLElement>(null),refs=useRef<(HTMLElement|null)[]>([]);const go=(i:number)=>refs.current[i]?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)'),u=()=>setReduced(m.matches);u();m.addEventListener('change',u);return()=>m.removeEventListener('change',u)},[]);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>=.55){const i=Number((e.target as HTMLElement).dataset.index);setActive(i);history.replaceState(null,'',`#sec0${i+1}`)}}),{root:scroll.current,threshold:[.55]});refs.current.forEach(s=>s&&o.observe(s));return()=>o.disconnect()},[]);
 return <div ref={root} className="experience"><div className="universe"><SceneBoundary><Canvas eventSource={root} eventPrefix="client" camera={{position:[0,0,16],fov:43}} dpr={[1,1.5]} gl={{alpha:true}}><Camera active={active} reduced={reduced}/><Galaxy/>{galaxyLinks.map((x,i)=><SectionLight key={x.name} item={x} index={i} active={active} reduced={reduced} onChoose={go}/>)}</Canvas></SceneBoundary></div>
 <header className="header"><a href="#sec01" onClick={e=>{e.preventDefault();go(0)}} className="brand"><strong>SRGH<span>.</span></strong><small>IT Team</small></a><span className="team-label">INFORMATION AND COMMUNICATION TECHNOLOGY</span></header>
 <nav className="roadmap-nav" aria-label="페이지 메뉴"><div className="roadmap-line"/>{roadmap.map(s=><a key={s.name} href={`#sec0${s.target+1}`} aria-current={active===s.target?'location':undefined} onClick={e=>{e.preventDefault();go(s.target)}}><i><span/></i><span className="roadmap-copy"><small>0{s.target+1} · {s.english}</small><strong>{s.name}</strong></span></a>)}</nav>
 <main ref={scroll} className="section-scroll" aria-label="IT팀 소개">
 <section id="sec01" data-index="0" ref={n=>{refs.current[0]=n}} className="full-section intro-section"><h1 className="sr-only">SRGH IT Team</h1><div className="work-scope" aria-label="IT팀 업무 영역">{workItems.map(x=><span key={x.id}>{x.name}</span>)}</div></section>
 <section id="sec02" data-index="1" ref={n=>{refs.current[1]=n}} className={`full-section content-section ${active===1?'is-active':''}`}><div className="section-copy"><span className="section-kicker">01 · ABOUT</span><h2>현장과 기술을<br/>하나의 흐름으로.</h2><p>의료정보, 출입통제, 서버, 통신, 개발을 연결해 안정적인 업무 환경을 만들고 운영합니다.</p><div className="about-grid">{workItems.map((x,i)=><article key={x.id}><small>0{i+1}</small><strong>{x.name}</strong><p>{x.description}</p></article>)}</div></div></section>
 <section id="sec03" data-index="2" ref={n=>{refs.current[2]=n}} className={`full-section content-section ${active===2?'is-active':''}`}><div className="section-copy"><span className="section-kicker">02 · HISTORY</span><h2>기술로 쌓아온<br/>우리의 시간.</h2><p>시스템의 기반을 만들고, 현장의 요구에 맞춰 영역을 넓혀 왔습니다.</p><div className="history-list"><article><small>FOUNDATION</small><strong>운영 기반 구축</strong><p>서버와 통신 환경을 정비하고 안정적인 업무 기반을 마련했습니다.</p></article><article><small>EXPANSION</small><strong>업무 시스템 확장</strong><p>의료정보와 출입통제 등 현장 중심의 시스템을 연결했습니다.</p></article><article><small>NOW</small><strong>지속적인 개발과 개선</strong><p>더 나은 업무 경험을 위해 서비스를 만들고 운영합니다.</p></article></div></div></section></main>
 <button className="scroll-cue" onClick={()=>go(active===2?0:active+1)}><ArrowDown size={16}/><span>{active===2?'처음으로':'다음'}</span></button></div>
}
