'use client';
import {Component,useEffect,useRef,useState,type ReactNode} from 'react';
import {Canvas,useFrame} from '@react-three/fiber';
import {Html} from '@react-three/drei';
import {AdditiveBlending,Color,Vector3,type Group} from 'three';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {Galaxy} from './galaxy';
import {workItems} from './services';
const colors=['#39c8ff','#ffd84a','#ff5a70'];
const roadmap=[{name:'메인',english:'HOME',target:0},{name:'소개',english:'ABOUT',target:1},{name:'연혁',english:'HISTORY',target:2}];
type GalaxyLink={name:string;position:[number,number,number];target:number|null;href?:string};
const galaxyLinks:GalaxyLink[]=[{name:'소개',position:[-3.7,.9,0],target:1},{name:'개발 · 배포',position:[2.55,-1.3,-.4],target:null,href:'/develop'},{name:'연혁',position:[3.8,1.15,-.5],target:2}];
type HistorySystem={id:string;title:string;desc:string;date:string;port:number};
const historyPaths:Record<number,string>={3000:'/work',3001:'/management',3002:'/rad',3003:'/qps',3004:'/insa',3005:'/history',3006:'/register',3007:'/worklog',3010:'/notice'};
const defaultHistorySystems:HistorySystem[]=[
 {id:'work',title:'Work System',desc:'IT팀 업무일지 대시보드',date:'2025.01',port:3000},
 {id:'mgmt',title:'Management',desc:'IT팀 자산관리 대시보드',date:'2025.02',port:3001},
 {id:'rad',title:'RAD Core',desc:'영상의학 처방별 가격 대시보드',date:'2025.04',port:3002},
 {id:'qps',title:'QPS Dashboard',desc:'QPS 환자 조회 대시보드',date:'2025.04',port:3003},
 {id:'insa',title:'Insa Dashboard',desc:'직원 관리 대시보드',date:'2026.01',port:3004},
 {id:'notice',title:'Notice Board',desc:'사내 통합 메뉴얼 홈페이지',date:'2026.06',port:3010},
 {id:'access',title:'Server Access Log',desc:'서버 출입대장',date:'2026.07',port:3006},
];
class SceneBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?null:this.props.children}}
function SectionLight({item,index,active,reduced,onChoose}:{item:GalaxyLink;index:number;active:number;reduced:boolean;onChoose:(i:number)=>void}){
 const group=useRef<Group>(null),target=useRef(new Vector3()),scale=useRef(new Vector3());
 useFrame(({clock,size},delta)=>{if(!group.current)return;const mobile=size.width<700;target.current.set(item.position[0]*(mobile?.55:1.15),item.position[1]*(mobile?1.05:1.25),item.position[2]);if(!reduced)target.current.y+=Math.sin(clock.elapsedTime*.35+index)*.07;group.current.position.lerp(target.current,reduced?1:Math.min(delta*3.5,1));scale.current.setScalar(active===0?1:.25);group.current.scale.lerp(scale.current,reduced?1:Math.min(delta*3,1))});
 const activate=()=>{if(item.href){location.href=item.href}else if(item.target!==null){onChoose(item.target)}};
 return <group ref={group} position={item.position}><mesh onClick={activate}><planeGeometry args={[2.2,2.2]}/><shaderMaterial transparent depthWrite={false} blending={AdditiveBlending} toneMapped={false} uniforms={{lightColor:{value:new Color(colors[index])}}} vertexShader={'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'} fragmentShader={'uniform vec3 lightColor;varying vec2 v;void main(){vec2 p=v-.5;float r=length(p);float h=exp(-r*9.0)*.65;float c=exp(-r*r*1500.0);float x=(exp(-abs(p.x)*170.0)*exp(-abs(p.y)*14.0)+exp(-abs(p.y)*170.0)*exp(-abs(p.x)*14.0))*.5;float a=min(1.0,h+c+x);gl_FragColor=vec4(mix(lightColor,vec3(1.0),c*.76),a);}'}/></mesh>{active===0&&<Html center position={[0,-.6,.1]} zIndexRange={[5,0]}>{item.href?<a className="section-light-label" href={item.href}><strong>{item.name}</strong><ArrowUpRight size={14}/></a>:<button className="section-light-label" onClick={activate}><strong>{item.name}</strong><ArrowUpRight size={14}/></button>}</Html>}</group>
}
function Camera({active,reduced}:{active:number;reduced:boolean}){const target=useRef(new Vector3());useFrame(({camera,pointer,size},delta)=>{const centerX=size.width<700?-.3:-.7;target.current.set(centerX+(reduced?0:pointer.x*.7),reduced?0:pointer.y*.35,(active?15:16)*Math.max(1,.85/(size.width/size.height)));camera.position.lerp(target.current,reduced?1:Math.min(delta*1.2,1));camera.lookAt(0,0,0)});return null}
export default function Home(){
 const[active,setActive]=useState(0),[reduced,setReduced]=useState(false),[historySystems,setHistorySystems]=useState<HistorySystem[]>(defaultHistorySystems),[protectedHref,setProtectedHref]=useState<string|null>(null),[password,setPassword]=useState(''),[passwordError,setPasswordError]=useState(false);const root=useRef<HTMLDivElement>(null!),scroll=useRef<HTMLElement>(null),refs=useRef<(HTMLElement|null)[]>([]);const go=(i:number)=>refs.current[i]?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});const closePassword=()=>{setProtectedHref(null);setPassword('');setPasswordError(false)};const openProtected=(href:string)=>{setProtectedHref(href);setPassword('');setPasswordError(false)};const submitPassword=(e:React.FormEvent)=>{e.preventDefault();if(password==='love!@0924'&&protectedHref){location.href=protectedHref;return}setPasswordError(true)};
 useEffect(()=>{const m=matchMedia('(prefers-reduced-motion: reduce)'),u=()=>setReduced(m.matches);u();m.addEventListener('change',u);return()=>m.removeEventListener('change',u)},[]);
 useEffect(()=>{const load=()=>{try{const raw=localStorage.getItem('portal_systems');if(!raw){setHistorySystems(defaultHistorySystems);return}const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw new Error('invalid history');setHistorySystems(parsed.filter((x):x is HistorySystem=>x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.desc==='string'&&typeof x.date==='string'&&Number.isFinite(Number(x.port))).map(x=>({...x,port:Number(x.port)})).sort((a,b)=>a.date.localeCompare(b.date)))}catch{setHistorySystems(defaultHistorySystems)}};load();const storage=(e:StorageEvent)=>{if(e.key==='portal_systems')load()};addEventListener('storage',storage);addEventListener('focus',load);document.addEventListener('visibilitychange',load);return()=>{removeEventListener('storage',storage);removeEventListener('focus',load);document.removeEventListener('visibilitychange',load)}},[]);
 useEffect(()=>{if(!protectedHref)return;const closeOnEscape=(e:KeyboardEvent)=>{if(e.key==='Escape')closePassword()};addEventListener('keydown',closeOnEscape);return()=>removeEventListener('keydown',closeOnEscape)},[protectedHref]);
 useEffect(()=>{if(location.hash)history.replaceState(null,'',`${location.pathname}${location.search}`);const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>=.55){const i=Number((e.target as HTMLElement).dataset.index);setActive(i)}}),{root:scroll.current,threshold:[.55]});refs.current.forEach(s=>s&&o.observe(s));return()=>o.disconnect()},[]);
 return <div ref={root} className="experience"><div className="universe"><SceneBoundary><Canvas eventSource={root} eventPrefix="client" camera={{position:[0,0,16],fov:43}} dpr={[1,1.5]} gl={{alpha:true}}><Camera active={active} reduced={reduced}/><Galaxy/>{galaxyLinks.map((x,i)=><SectionLight key={x.name} item={x} index={i} active={active} reduced={reduced} onChoose={go}/>)}</Canvas></SceneBoundary></div>
 <header className="header"><a href="/" onClick={e=>{e.preventDefault();go(0)}} className="brand"><strong>SRGH IT Team</strong></a><span className="team-label">INFORMATION AND COMMUNICATION TECHNOLOGY</span></header>
 <nav className="roadmap-nav" aria-label="페이지 메뉴"><div className="roadmap-line"/>{roadmap.map(s=><a key={s.name} href="/" aria-current={active===s.target?'location':undefined} onClick={e=>{e.preventDefault();go(s.target)}}><i><span/></i><span className="roadmap-copy"><small>0{s.target+1} · {s.english}</small><strong>{s.name}</strong></span></a>)}</nav>
 <main ref={scroll} className="section-scroll" aria-label="IT팀 소개">
 <section id="sec01" data-index="0" ref={n=>{refs.current[0]=n}} className="full-section intro-section"><h1 className="sr-only">SRGH IT Team</h1><div className="work-scope" aria-label="IT팀 업무 영역">{workItems.map(x=><span key={x.id}>{x.name}</span>)}</div></section>
 <section id="sec02" data-index="1" ref={n=>{refs.current[1]=n}} className={`full-section content-section ${active===1?'is-active':''}`}><div className="section-copy"><h2>ABOUT</h2><div className="about-grid">{workItems.map((x,i)=><article key={x.id}><small>0{i+1}</small><strong>{x.name}</strong><p>{x.description}</p></article>)}</div></div></section>
 <section id="sec03" data-index="2" ref={n=>{refs.current[2]=n}} className={`full-section content-section history-section ${active===2?'is-active':''}`}><div className="section-copy"><h2>HISTORY</h2><div className="history-list">{historySystems.map(item=>{const href=historyPaths[item.port]??`http://${location.hostname}:${item.port}`;return <a className="history-card-link" key={item.id} href={href} aria-label={`${item.title} 사이트로 이동`} onClick={e=>{e.preventDefault();openProtected(href)}}><article><small>{item.date}</small><strong>{item.title}</strong><p>{item.desc}</p><ArrowUpRight className="history-card-arrow" size={17} aria-hidden="true"/></article></a>})}</div></div></section></main>
 {protectedHref&&<div className="password-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)closePassword()}}><form className="password-dialog" role="dialog" aria-modal="true" aria-labelledby="password-title" onSubmit={submitPassword}><button className="password-close" type="button" aria-label="닫기" onClick={closePassword}>×</button><small>SECURE ACCESS</small><h3 id="password-title">비밀번호를 입력하세요</h3><input autoFocus type="password" value={password} onChange={e=>{setPassword(e.target.value);setPasswordError(false)}} placeholder="비밀번호" aria-invalid={passwordError}/>{passwordError&&<p role="alert">비밀번호가 올바르지 않습니다.</p>}<button className="password-submit" type="submit">확인</button></form></div>}
 <button className="scroll-cue" onClick={()=>go(active===2?0:active+1)}><ArrowDown size={16}/><span>{active===2?'처음으로':'다음'}</span></button></div>
}
